import { prisma } from "@/server/db";

export async function getWorldModelAxioms(organizationId: string) {
  const existing = await prisma.worldModelAxiom.findMany({
    where: { organizationId },
    orderBy: { verifiedAt: "desc" },
  });

  if (existing.length > 0) return existing;

  const defaultAxioms = [
    {
      organizationId,
      title: "Inconel 718 Laser Warpage Energy Bound",
      description:
        "Neuro-symbolic SAT check mapping laser power draw to thermal gradients and warpage thresholds.",
      logicPredicate:
        "∀x (IsPart(x) ∧ Material(x, Inconel718) ∧ LaserPower(x) > 380W → Warpage(x) > 0.05mm)",
      confidence: 0.98,
    },
    {
      organizationId,
      title: "DMG Mori Spindle Mechanical Frequency",
      description:
        "Chatter resonance limit axiom generated by correlating rotational frequency with rib deflection rates.",
      logicPredicate: "∀s ∀f (Spindle(s) ∧ RotSpeed(s, 11200rpm) → VibrationResonance(s) = PASS)",
      confidence: 0.95,
    },
  ];

  const created = [];
  for (const a of defaultAxioms) {
    const item = await prisma.worldModelAxiom.create({ data: a });
    created.push(item);
  }

  return created;
}

export async function runSatSolver(organizationId: string, axiomId: string) {
  const axiom = await prisma.worldModelAxiom.findFirst({
    where: { id: axiomId, organizationId },
  });

  if (!axiom) throw new Error("Axiom not found");

  return prisma.worldModelAxiom.update({
    where: { id: axiomId },
    data: { confidence: 0.99 },
  });
}
